name: Doc Publish
on:
  push:
    branches:
    - master
    
jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 'stable'
          target: 'x86_64-unknown-linux-gnu'
      - name: Cargo Doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --verbose --no-deps --document-private-items
