name: Doc Publish
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Install Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 'stable'
          target: 'x86_64-unknown-linux-gnu'
      - name: Cargo Doc
        run: cargo doc --verbose --no-deps --document-private-items
