on:
  workflow_dispatch:
    inputs:
      version:
          description: Version to release
          required: true
          type: string

permissions:
  # TODO: once `releases: write` is supported, use it instead.
  contents: write

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cargo-release
      - uses: tibdex/github-app-token@v2.1.0
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_SECRET_KEY }}
      - uses: oleksiyrudenko/gha-git-credentials@v2.1.1
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - run: cargo release ${{ inputs.version }} --execute --verbose --no-confirm
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
