on:
  workflow_dispatch:
  schedule:
    - cron:  '7 5 1 * *'

name: Update

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run:  cargo install svd2rust
      - run:  cargo install form
      - uses: oleksiyrudenko/gha-git-credentials@v2.1.2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - shell: bash
        run: ./svd.sh
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_SECRET_KEY }}
      - uses: peter-evans/create-pull-request@v7
        with:
          branch: svd-update
          commit-message: "feat: updating from newer svd2rust"
          title: "feat: updating from newer svd2rust"
          labels: automerge
          token: ${{ steps.generate-token.outputs.token }}
